---

- name: Pull PostgreSql server docker image
  community.docker.docker_image:
    name: "{{ pg_server_docker_image }}"
    source: pull

- name: Create PostgreSql server docker container
  community.docker.docker_container:
    name: "{{ pg_server_docker_container_name }}"
    image: "{{ pg_server_docker_image }}"
    ports: "{{ pg_server_docker_port }}:5432"
    volumes:
      - "{{ pg_server_docker_volume_name }}:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "{{ pg_server_sa_name }}"
      POSTGRES_PASSWORD: "{{ pg_server_sa_password }}"
    restart_policy: "always"
    state: started