---

- name: Create a new database for SAWalk app
  community.postgresql.postgresql_db:
    login_host: "{{ ansible_host }}"
    port: "{{ pg_server_docker_port }}"
    login_user: "{{ pg_server_sa_name }}"
    login_password: "{{ pg_server_sa_password }}"
    name: "{{ sawalk_app_db.name.dev }}"
    force: true
    state: present

- name: Create a new user for SAWalk app
  community.postgresql.postgresql_user:
    login_host: "{{ ansible_host }}"
    port: "{{ pg_server_docker_port }}"
    login_user: "{{ pg_server_sa_name }}"
    login_password: "{{ pg_server_sa_password }}"
    db: "{{ sawalk_app_db.name.dev }}"
    name: "{{ sawalk_app_db.user_name.dev }}"
    password: "{{ sawalk_app_db.user_password.dev }}"
    state: present

- name: GRANT ALL PRIVILEGES ON DATABASE library TO librarian
  community.postgresql.postgresql_privs:
    login_host: "{{ ansible_host }}"
    port: "{{ pg_server_docker_port }}"
    login_user: "{{ pg_server_sa_name }}"
    login_password: "{{ pg_server_sa_password }}"
    db: "{{ sawalk_app_db.name.dev }}"
    privs: ALL
    type: database
    role: "{{ sawalk_app_db.user_name.dev }}"
    state: present