---

- name: Create dev db for vaccine app
  community.general.mssql_db:
    name: "{{ vaccine_app_db.name.dev }}"
    login_host: "{{ ansible_host }}"
    login_port: "{{ sql_server_docker_port }}"
    login_user: "{{ sql_server_sa_name }}"
    login_password: "{{ sql_server_sa_password }}"
    autocommit: true
    state: present

- name: Create dev user for vaccine app db
  community.general.mssql_script:
    login_host: "{{ ansible_host }}"
    login_port: "{{ sql_server_docker_port }}"
    login_user: "{{ sql_server_sa_name }}"
    login_password: "{{ sql_server_sa_password }}"
    db: master
    script: |
      IF NOT EXISTS
      (
        SELECT 1
        FROM master.sys.server_principals
        WHERE name = '{{ vaccine_app_db.user_name.dev }}'
      )
      BEGIN
        SET NOCOUNT ON;
        CREATE LOGIN {{ vaccine_app_db.user_name.dev }} 
        WITH PASSWORD = %(user_password)s, 
        DEFAULT_DATABASE = {{ vaccine_app_db.name.dev }};
        ALTER LOGIN {{ vaccine_app_db.user_name.dev }} ENABLE;
      END
      SELECT 0;
    params:
      user_password: "{{ vaccine_app_db.user_password.dev }}"

- name: Grant user permissions for vaccine app db
  community.general.mssql_script:
    login_host: "{{ ansible_host }}"
    login_port: "{{ sql_server_docker_port }}"
    login_user: "{{ sql_server_sa_name }}"
    login_password: "{{ sql_server_sa_password }}"
    db: master
    script: |
      SET NOCOUNT ON;
      USE [ProceduresDev];
      IF NOT EXISTS(
        SELECT 1
        FROM sys.database_permissions
        WHERE USER_NAME(grantee_principal_id) = '{{ vaccine_app_db.user_name.dev }}')
       BEGIN
        SET ANSI_NULLS ON;
        SET QUOTED_IDENTIFIER ON;
        IF NOT EXISTS(
          SELECT 1 
          FROM sys.database_principals 
          WHERE name = N'{{ vaccine_app_db.user_name.dev }}')
          CREATE USER {{ vaccine_app_db.user_name.dev }} 
            FOR LOGIN {{ vaccine_app_db.user_name.dev }};
        ALTER USER [{{ vaccine_app_db.user_name.dev }}] WITH DEFAULT_SCHEMA=[dbo]
        ALTER ROLE [db_owner] ADD MEMBER [{{ vaccine_app_db.user_name.dev }}]
        GRANT ALTER ANY SCHEMA TO {{ vaccine_app_db.user_name.dev }};
        GRANT EXECUTE TO {{ vaccine_app_db.user_name.dev }};
        EXEC sp_addrolemember N'db_datareader', N'{{ vaccine_app_db.user_name.dev }}';
        EXEC sp_addrolemember N'db_datawriter', N'{{ vaccine_app_db.user_name.dev }}';
        EXEC sp_addrolemember N'db_ddladmin', N'{{ vaccine_app_db.user_name.dev }}';
       END
      SELECT 0;
